Repository LT-Students/DigitalOffice-TimeService, pull requests merged in 2021-07, with the labels that each got.

#19 Change class to record of dto models
  src/TimeService.Models.Dto/Models/LeaveTimeInfo.cs
  src/TimeService.Models.Dto/Models/WorkTimeInfo.cs
  src/TimeService.Models.Dto/Requests/CreateLeaveTimeRequest.cs
  src/TimeService.Models.Dto/Requests/CreateWorkTimeRequest.cs
  src/TimeService.Models.Dto/Requests/EditWorkTimeRequest.cs
  src/TimeService.Models.Dto/Requests/HelpersModels/EditWorkTimeModel.cs
  src/TimeService.Models.Dto/Responses/LeaveTimesResponse.cs
  src/TimeService.Models.Dto/Responses/WorkTimesResponse.cs
Labels: enhancement

#20 fix github actions
  .github/workflows/main.yml
Labels: documentation

#22 fixed pagination
  Common.Configurations.targets
  src/TimeService.Data/Interfaces/ILeaveTimeRepository.cs
  src/TimeService.Data/Interfaces/IWorkTimeRepository.cs
  src/TimeService.Data/LeaveTimeRepository.cs
  src/TimeService.Data/WorkTimeRepository.cs
Labels: bug

#23 docs/change_actions
  .github/workflows/main.yml
Labels: documentation

#24 bug/fix validator
  src/TimeService.Mappers/Db/DbLeaveTimeMapper.cs
  src/TimeService.Mappers/Db/DbWorkTimeMapper.cs
  src/TimeService.Validation/CreateLeaveTimeRequestValidator.cs
  src/TimeService.Validation/EditWorkTimeRequestValidator.cs
  test/TimeService.Validation.UnitTests/CreateLeaveTimeRequestValidatorTests.cs
Labels: bug
