Repository LT-Students/DigitalOffice-TimeService, pull requests merged in 2022-11, with the labels that each got.

#146 remove images
  src/TimeService.Broker/Requests/ImageService.cs
  src/TimeService.Broker/Requests/Interfaces/IImageService.cs
  src/TimeService.Business/Commands/Stat/FindStatCommand.cs
  src/TimeService.Mappers/Models/Interfaces/IUserInfoMapper.cs
  src/TimeService.Mappers/Models/UserInfoMapper.cs
  src/TimeService.Models.Dto/Models/UserInfo.cs
  src/TimeService/Startup.cs
  test/TimeService.Business.UnitTests/Commands/Stat/FindStatCommandTests.cs
Labels: enhancement

#147 update redis keys
  Common.Configurations.targets
  src/TimeService.Broker/Requests/CompanyService.cs
  src/TimeService.Broker/Requests/DepartmentService.cs
  src/TimeService.Broker/Requests/PositionService.cs
  src/TimeService.Broker/Requests/ProjectService.cs
  src/TimeService.Broker/Requests/UserService.cs
Labels: bug

#149 fix LeaveTimeIntervalValidator, update allowed days to edit previos month
  src/TimeService.Business/Commands/LeaveTime/EditLeaveTimeCommand.cs
  src/TimeService.Business/Helpers/Emails/EmailSender.cs
  src/TimeService.Data/LeaveTimeRepository.cs
  src/TimeService.Validation/LeaveTime/LeaveTimeIntervalValidator.cs
Labels: bug, enhancement

#150 add comments to stat table, update colors
  Common.Configurations.targets
  src/TimeService.Business/Commands/Import/ImportStatCommand.cs
Labels: enhancement

#151 fix comments, update wt validation
  src/TimeService.Business/Commands/Import/ImportStatCommand.cs
  src/TimeService.Validation/WorkTime/CreateWorkTimeRequestValidator.cs
  src/TimeService.Validation/WorkTime/EditWorkTimeRequestValidator.cs
Labels: enhancement

#152 add pending users to stat/find and import/stat results
  Common.Configurations.targets
  src/TimeService.Broker/Requests/DepartmentService.cs
  src/TimeService.Broker/Requests/Interfaces/IDepartmentService.cs
  src/TimeService.Business/Commands/Import/ImportStatCommand.cs
  src/TimeService.Business/Commands/Stat/FindStatCommand.cs
  src/TimeService.Mappers/Models/Interfaces/IUserInfoMapper.cs
  src/TimeService.Mappers/Models/UserInfoMapper.cs
  src/TimeService.Models.Dto/Models/UserInfo.cs
  src/TimeService/Startup.cs
  test/TimeService.Business.UnitTests/Commands/Stat/FindStatCommandTests.cs
Labels: enhancement

#153 add project filter to stat/find, disable 90 degree rotate for the first three columns' headers in stat table
  src/TimeService.Business/Commands/Import/ImportStatCommand.cs
  src/TimeService.Business/Commands/Stat/FindStatCommand.cs
  src/TimeService.Mappers/Models/LeaveTimeInfoMapper.cs
  src/TimeService.Models.Dto/Filters/FindStatFilter.cs
  src/TimeService.Models.Dto/Models/LeaveTimeInfo.cs
  src/TimeService.Validation/Stat/FindStatFilterValidator.cs
  src/TimeService/Startup.cs
  test/TimeService.Business.UnitTests/Commands/Stat/FindStatCommandTests.cs
Labels: enhancement

#154 add isActive to GetProjectsUsersAsync, remove LeaveType from EditLeaveTimeRequest
  Common.Configurations.targets
  src/TimeService.Broker/Requests/Interfaces/IProjectService.cs
  src/TimeService.Broker/Requests/ProjectService.cs
  src/TimeService.Business/Commands/Import/ImportStatCommand.cs
  src/TimeService.Business/Commands/LeaveTime/Helpers/LeaveTimeAccessValidationHelper.cs
  src/TimeService.Business/Commands/Stat/FindStatCommand.cs
  src/TimeService.Business/Helpers/Workdays/WorkTimeCreator.cs
  src/TimeService.Mappers/Patch/PatchDbLeaveTimeMapper.cs
  src/TimeService.Models.Dto/Requests/EditLeaveTimeRequest.cs
  src/TimeService.Validation/LeaveTime/EditLeaveTimeRequestValidator.cs
  test/TimeService.Business.UnitTests/Commands/Stat/FindStatCommandTests.cs
Labels: bug, enhancement

#155 added to resx message for LeaveTime minutes
  src/TimeService.Validation/LeaveTime/CreateLeaveTimeRequestValidator.cs
  src/TimeService.Validation/LeaveTime/Resources/LeaveTimeValidatorResource.Designer.cs
  src/TimeService.Validation/LeaveTime/Resources/LeaveTimeValidatorResource.resx
  src/TimeService.Validation/LeaveTime/Resources/LeaveTimeValidatorResource.ru-RU.resx
Labels: bug
